### ISSUE TITLE
[Bug] Server Name is not displaying correctly

### ISSUE THREAD

**Issue by AllOutJay** [hypherionmc/sdlink#16]
Minecraft version:
Minecraft 1.19

Mod Version:
SimpleDiscordLink-fabric-1.19-1.4.0.jar

Description of the issue:
After updating to the new mod, deleting the old config, and setting up the new config, the "Server" bot doesn't have the right name.

![Image of the serverName defaulting to "server" despite being marked as "AfterLife".](https://user-images.githubusercontent.com/80604256/182972872-f5e6f759-99a6-418c-88c8-a4f7d6852865.png)
Attached config: [simple-discord-bot.txt](https://github.com/hypherionmc/sdlink/files/9264118/simple-discord-bot.txt)

**Comment by hypherionmc** [comment]
For fudge sakes... This is why I leave the test builds out before a release, but doesn't seem like anyone aside from me tested them. Does this only happen with Webhooks or with normal messages as well?

**Comment by AllOutJay** [comment]
The Server's name doesn't display correctly in the normal messages either.
![image](https://user-images.githubusercontent.com/80604256/183088317-520dd5a7-3b6f-4259-b710-473ddf1f8ac8.png)

**Comment by hypherionmc** [comment]
Issue was fixed a while ago in our snapshot builds, but release 2.0 contains the fix as well

**Comment by PolyframeX** [comment]
This issue has re appeared, I am using the Fabric 1.20 latest build (1.20-2.2.3) and this issue is still occuring.
[simple-discord-bot.txt](https://github.com/hypherionmc/sdlink/files/12709715/simple-discord-bot.txt)

**Comment by hypherionmc** [comment]
Yes, I messed up some of the code. The fix for now is to use 2.2.2.
